update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(bronzeYnJvbnpl)''bronze''' where material ='bronze';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(teakdGVhaw)''teak''' where material ='teak';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(decalZGVjYWw)''decal''' where material ='decal';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='giclee archival paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ramiecmFtaWU)''ramie''' where material ='ramie (wool)';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(silkc2lsaw)''silk''' where material ='silk';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(chinaY2hpbmE)''china''' where material ='china';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(watercolord2F0ZXJjb2xvcg)''watercolor''' where material ='watercolor';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hardwoodaGFyZHdvb2Q)''hard wood''' where material ='hard wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(limestonebGltZXN0b25l)''limestone''' where material ='lime stone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(chinaY2hpbmE)''china''' where material ='ceramic/clay/china';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(inkaW5r)''ink''' where material ='woodblock prints on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(tracingpaperdHJhY2luZ3BhcGVy)''tracing paper''' where material ='graphite on tracing paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(coinsY29pbnM)''coins''' where material ='coins';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(polychromeglassbeadscG9seWNocm9tZWdsYXNzYmVhZHM)''polychrome glass beads''' where material ='plolychrome beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(enamelZW5hbWVs)''enamel''' where material ='enamel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(mirrorglassbWlycm9yZ2xhc3M)''mirror glass''' where material ='mirror glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cowrieY293cmll)''cowrie''' where material ='Cowries';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='penicl on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stonec3RvbmU)''stone''' where material ='stone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='gelatin silver print';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(silkc2lsaw)''silk''' where material ='slik';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(yarneWFybg)''yarn''' where material ='yarn';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(nailsbmFpbHM)''nails''' where material ='nails';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cowrieY293cmll)''cowrie''' where material ='cowries';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(schistc2NoaXN0)''schist''' where material ='schist';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='gellatin silver paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='silver gelatine paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(beadsYmVhZHM)''beads''' where material ='beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pigmentcGlnbWVudA)''pigment''' where material ='pigment, white';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(staplesc3RhcGxlcw)''staples''' where material ='staples';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(jackfruitwoodamFja2ZydWl0d29vZA)''jack fruit wood''' where material ='jack fruit wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(booksYm9va3M)''books''' where material ='books (paper)';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(handstoneaGFuZHN0b25l)''hand stone''' where material ='hand stone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(limebGltZQ)''lime''' where material ='lime';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(silkc2lsaw)''silk''' where material ='sillk';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hippopotamusleatheraGlwcG9wb3RhbXVzbGVhdGhlcg)''hippopotamus leather''' where material ='hippopotamus leather';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(bananafiberYmFuYW5hZmliZXI)''banana fiber''' where material ='banane fiber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(barkYmFyaw)''bark''' where material ='bark';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='Paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(polychromewoodcG9seWNocm9tZXdvb2Q)''polychrome wood''' where material ='Polychrome wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pencilcGVuY2ls)''pencil''' where material ='colored pencil';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='gelatine silver print';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(graphpaperZ3JhcGhwYXBlcg)''graph paper''' where material ='pencil and ink on graph paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plywoodcGx5d29vZA)''plywood''' where material ='Plywood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(goldstringZ29sZHN0cmluZw)''gold string''' where material ='gold string';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(shellc2hlbGw)''shell''' where material ='shells';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(vellumdmVsbHVt)''vellum''' where material ='Marker on vellum';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(bambooYmFtYm9v)''bamboo''' where material ='bamboo';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(metalbWV0YWw)''metal''' where material ='Metal';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(veneerdmVuZWVy)''veneer''' where material ='veneer';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelrodc3RlZWxyb2Q)''steel rod''' where material ='nickle-plated metal rod';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(softpasteporcelainc29mdHBhc3RlcG9yY2VsYWlu)''soft paste porcelain''' where material ='soft paste porcelain';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(motherofpearlbW90aGVyb2ZwZWFybA)''mother of pearl''' where material ='mother pearl shell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stringc3RyaW5n)''string''' where material ='fiber string';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glassZ2xhc3M)''glass''' where material ='glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(faienceZmFpZW5jZQ)''faience''' where material ='Fayence';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(horsehairaG9yc2VoYWly)''horsehair''' where material ='horsehair';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(coppertackY29wcGVydGFjaw)''copper tack''' where material ='coppertacks';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(chickenfeatherY2hpY2tlbmZlYXRoZXI)''chicken feather''' where material ='chicken feathers';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(mahoganybWFob2dhbnk)''mahogany''' where material ='mahogany';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(shogwiyawtreec2hvZ3dpeWF3dHJlZQ)''shogwiyaw tree''' where material ='shogwiyaw tree';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(coppertackY29wcGVydGFjaw)''copper tack''' where material ='copper tacks';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(vulcanictuffdnVsY2FuaWN0dWZm)''vulcanic tuff''' where material ='vulcanic Tuff';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(riverstonecml2ZXJzdG9uZQ)''river stone''' where material ='river stone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(MDFpanelTURGcGFuZWw)''MDF panel''' where material ='MDF panel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(mangantonbWFuZ2FudG9u)''manganton''' where material ='mangaton';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glassbeadsZ2xhc3NiZWFkcw)''glass beads''' where material ='Glass beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='teracotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(vinyldmlueWw)''vinyl''' where material ='vinyl';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='terrakotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(paintcGFpbnQ)''paint''' where material ='Paint';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woold29vbA)''wool''' where material ='wool';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plywoodcGx5d29vZA)''plywood''' where material ='oil on plywood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(naturaldyebmF0dXJhbGR5ZQ)''natural dye''' where material ='Natural Dye';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(beadsYmVhZHM)''beads''' where material ='blue, white and red beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plasticcGxhc3RpYw)''plastic''' where material ='plastic';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(barkYmFyaw)''bark''' where material ='Bork';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='Duotone lithograph';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='fibers';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(faienceZmFpZW5jZQ)''faience''' where material ='faience';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glasswareZ2xhc3N3YXJl)''glassware''' where material ='glassware';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='paper flowers';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(adhesiveYWRoZXNpdmU)''adhesive''' where material ='adhesive';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(canvasY2FudmFz)''canvas''' where material ='Oil on Canvas';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='Black ink and ballpoint on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(vellumdmVsbHVt)''vellum''' where material ='Platinum print on canson vellum';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(walnutwoodd2FsbnV0d29vZA)''walnut wood''' where material ='walnut wood (base)';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glassbeadsZ2xhc3NiZWFkcw)''glass beads''' where material ='glass beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pigmentcGlnbWVudA)''pigment''' where material ='Pigment';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(coconutY29jb251dA)''coconut''' where material ='cocnut shell beads';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cardboardY2FyZGJvYXJk)''cardboard''' where material ='oil on cardboard';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(alabasterYWxhYmFzdGVy)''alabaster''' where material ='Alabaster';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='pastel on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fabricZmFicmlj)''fabric''' where material ='fabric';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelc3RlZWw)''steel''' where material ='steel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fabricZmFicmlj)''fabric''' where material ='fabiric';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ivoryaXZvcnk)''ivory''' where material ='ivory';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(feltZmVsdA)''felt''' where material ='felt';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(redpigmentcmVkcGlnbWVudA)''red pigment''' where material ='red pigment';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(chalkY2hhbGs)''chalk''' where material ='chalk';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(polarbearbonecG9sYXJiZWFyYm9uZQ)''polar bear bone''' where material ='polar bear bone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(copperY29wcGVy)''copper''' where material ='copper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(leatherbGVhdGhlcg)''leather''' where material ='yellow Leather';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cottonY290dG9u)''cotton''' where material ='cotton';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plywoodcGx5d29vZA)''plywood''' where material ='plywood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(whaleboned2hhbGVib25l)''whale bone''' where material ='jaw bone of sperm whale';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(limepigmentbGltZXBpZ21lbnQ)''lime pigment''' where material ='lime Pigment';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='Terracotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(porcelaincG9yY2VsYWlu)''porcelain''' where material ='porcelian';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(maplewoodbWFwbGV3b29k)''maple wood''' where material ='maple wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='oil on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='fiber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(palmwoodcGFsbXdvb2Q)''palm wood''' where material ='palm wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(furZnVy)''fur''' where material ='fur';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(walrustoothd2FscnVzdG9vdGg)''walrus tooth''' where material ='walruss tooth';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='textiles';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(porcelaincG9yY2VsYWlu)''porcelain''' where material ='porcelaine';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='oil on board';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelpipec3RlZWxwaXBl)''steel pipe''' where material ='steel pipe';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(velvetdmVsdmV0)''velvet''' where material ='velvet';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(linocutonpaperbGlub2N1dG9ucGFwZXI)''linocut on paper''' where material ='linocut on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(limewoodbGltZXdvb2Q)''lime wood''' where material ='lime wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(mangrovewoodbWFuZ3JvdmV3b29k)''mangrove wood''' where material ='mangrove wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(sandc2FuZA)''sand''' where material ='sand';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plasticcGxhc3RpYw)''plastic''' where material ='plastic layer';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cottonY290dG9u)''cotton''' where material ='cotton bast';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='photograph in gilded wooden frame';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stringc3RyaW5n)''string''' where material ='strings';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(raffiacmFmZmlh)''raffia''' where material ='Embroidered raffia';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='vintage gelatin silver print';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(canvasY2FudmFz)''canvas''' where material ='canvas board';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(dyeZHll)''dye''' where material ='dye';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(strawc3RyYXc)''straw''' where material ='straw';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='carved wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(dutchstringZHV0Y2hzdHJpbmc)''dutch string''' where material ='dutch string';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelc3RlZWw)''steel''' where material ='Steel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(tradeclothdHJhZGVjbG90aA)''trade cloth''' where material ='trade cloth';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glassZ2xhc3M)''glass''' where material ='Glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(oilpaintb2lscGFpbnQ)''oil paint''' where material ='oil on sheet';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stonec3RvbmU)''stone''' where material ='Stone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(tuskdHVzaw)''tusk''' where material ='tusk';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stuccoc3R1Y2Nv)''stucco''' where material ='stucco';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(oakb2Fr)''oak''' where material ='oak';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(mixedmediabWl4ZWRtZWRpYQ)''mixed media''' where material ='mixed media';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(PlexiglasUGxleGlnbGFz)''Plexiglas''' where material ='Plexiglas';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(turtleshelldHVydGxlc2hlbGw)''turtle shell''' where material ='turtleshell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cymbiumsnailY3ltYml1bXNuYWls)''cymbium snail''' where material ='cymbium snail';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ashwoodYXNod29vZA)''ash wood''' where material ='Ash wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelc3RlZWw)''steel''' where material ='lacquered tubular steel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='terra cotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pigmentcGlnbWVudA)''pigment''' where material ='pigments';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(rattancmF0dGFu)''rattan''' where material ='woven rattan';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(caseinY2FzZWlu)''casein''' where material ='casein';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(rattancmF0dGFu)''rattan''' where material ='ratan';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ceramicY2VyYW1pYw)''ceramic''' where material ='ceramic';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(rubbercnViYmVy)''rubber''' where material ='rubber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='Inlaid wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(leatherbGVhdGhlcg)''leather''' where material ='leather';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='textiles/fabric';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woold29vbA)''wool''' where material ='Wool';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(raffiacmFmZmlh)''raffia''' where material ='Raffia';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(graphpaperZ3JhcGhwYXBlcg)''graph paper''' where material ='pencil on graph paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hairaGFpcg)''hair''' where material ='hair';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberglassZmliZXJnbGFzcw)''fiberglass''' where material ='fiberglass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(paintcGFpbnQ)''paint''' where material ='paint';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(steelc3RlZWw)''steel''' where material ='perforated sheet steel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(porcelaincG9yY2VsYWlu)''porcelain''' where material ='Porcelain';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(grassZ3Jhc3M)''grass''' where material ='grass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fabricZmFicmlj)''fabric''' where material ='cloth';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(featherZmVhdGhlcg)''feather''' where material ='feathers';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(vellumdmVsbHVt)''vellum''' where material ='vellum';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(goldalloyZ29sZGFsbG95)''gold alloy''' where material ='gold alloy';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pencilcGVuY2ls)''pencil''' where material ='pencil';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(metalbarbWV0YWxiYXI)''metal bar''' where material ='metal bar';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='silver gelantine print';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hideaGlkZQ)''hide''' where material ='hide';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(instantfilmaW5zdGFudGZpbG0)''instant film''' where material ='polaroid paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(clayY2xheQ)''clay''' where material ='clay';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='single stick weave';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(shellc2hlbGw)''shell''' where material ='Shell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(inkaW5r)''ink''' where material ='ink';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(acrylicYWNyeWxpYw)''acrylic''' where material ='acryl';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pinewoodcGluZXdvb2Q)''pine wood''' where material ='pine wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(tuskdHVzaw)''tusk''' where material ='tusks';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(wickerd2lja2Vy)''wicker''' where material ='wicker';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(copperplateY29wcGVycGxhdGU)''copper plate''' where material ='copper plate';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ironaXJvbg)''iron''' where material ='iron';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(waxd2F4)''wax''' where material ='wax';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='Wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cardboardY2FyZGJvYXJk)''cardboard''' where material ='Corrugated cardboard';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(motherofpearlbW90aGVyb2ZwZWFybA)''mother of pearl''' where material ='mother pearl';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(waterbuffalohornd2F0ZXJidWZmYWxvaG9ybg)''water buffalo horn''' where material ='waterbuffalo horn';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ironwoodaXJvbndvb2Q)''iron wood''' where material ='iron wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stonewarec3RvbmV3YXJl)''stoneware''' where material ='stoneware';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cottonY290dG9u)''cotton''' where material ='Cotton';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(birchplywoodYmlyY2hwbHl3b29k)''birch plywood''' where material ='birch plywood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(leatherbGVhdGhlcg)''leather''' where material ='Leather';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(lightwoodbGlnaHR3b29k)''light wood''' where material ='light wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(castironY2FzdGlyb24)''cast iron''' where material ='cast iron';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(darkglassZGFya2dsYXNz)''dark glass''' where material ='dark glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(linenbGluZW4)''linen''' where material ='linen';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plasticsolecGxhc3RpY3NvbGU)''plastic sole''' where material ='plastic sole';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stringc3RyaW5n)''string''' where material ='string';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(shellc2hlbGw)''shell''' where material ='shell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(papercGFwZXI)''paper''' where material ='ink on paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(spondylusshellc3BvbmR5bHVzc2hlbGw)''spondylus shell''' where material ='spondylus shell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(newsprintbmV3c3ByaW50)''newsprint''' where material ='ink and gesso on newspaper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(marblebWFyYmxl)''marble''' where material ='marble, white';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(clayY2xheQ)''clay''' where material ='Clay';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(wovenfiberd292ZW5maWJlcg)''woven fiber''' where material ='woven fiber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(tracingpaperdHJhY2luZ3BhcGVy)''tracing paper''' where material ='pencil on tracing paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(foamZm9hbQ)''foam''' where material ='foam';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(caneY2FuZQ)''cane''' where material ='caning';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(buffalohornYnVmZmFsb2hvcm4)''buffalo horn''' where material ='Buffalo Horn';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(furZnVy)''fur''' where material ='bone/ivory/tooth/skin/leather/feather/fur';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(rattancmF0dGFu)''rattan''' where material ='rattan';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cottonY290dG9u)''cotton''' where material ='cotton fiber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fiberandtextileZmliZXJhbmR0ZXh0aWxl)''fiber and textile''' where material ='fibre';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ambertintedglassYW1iZXJ0aW50ZWRnbGFzcw)''amber tinted glass''' where material ='amber tinted glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(naturalfiberbmF0dXJhbGZpYmVy)''natural fiber''' where material ='natural fiber';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(masonitebWFzb25pdGU)''masonite''' where material ='corrugated paper (masonite)';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pubichaircHViaWNoYWly)''pubic hair''' where material ='pubic hair';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(canvasY2FudmFz)''canvas''' where material ='oil on canvas';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(lightgreenglassbGlnaHRncmVlbmdsYXNz)''light green glass''' where material ='light green glass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='stone polished terrakotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(glazedceramicZ2xhemVkY2VyYW1pYw)''glazed ceramic''' where material ='glazed ceramic';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(teakdGVhaw)''teak''' where material ='Teak';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cardboardY2FyZGJvYXJk)''cardboard''' where material ='cardboard';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(earthenwareZWFydGhlbndhcmU)''earthenware''' where material ='earthenware';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(leatherbGVhdGhlcg)''leather''' where material ='leater';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(syntheticfurc3ludGhldGljZnVy)''synthetic fur''' where material ='syntetic fur';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(boneYm9uZQ)''bone''' where material ='bone';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hardwoodaGFyZHdvb2Q)''hard wood''' where material ='hardwood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(naturaldyebmF0dXJhbGR5ZQ)''natural dye''' where material ='natural dyes';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(woodd29vZA)''wood''' where material ='wwod';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(metalstringbWV0YWxzdHJpbmc)''metal string''' where material ='metal string';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(linenbGluZW4)''linen''' where material ='oil on linen';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(fabricZmFicmlj)''fabric''' where material ='woven cloth';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(canvasY2FudmFz)''canvas''' where material ='canvas';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(ricepapercmljZXBhcGVy)''rice paper''' where material ='Watercolor on Yuan (rice) paper';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(chalkpigmentY2hhbGtwaWdtZW50)''chalk pigment''' where material ='chalk pigment';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(conchshellY29uY2hzaGVsbA)''conch shell''' where material ='Conch shell';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='Terrakotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(oilpaintb2lscGFpbnQ)''oil paint''' where material ='oilpaint';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(nickelbmlja2Vs)''nickel''' where material ='nickel';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pigmentcGlnbWVudA)''pigment''' where material ='pigment';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(paintcGFpbnQ)''paint''' where material ='paint on board';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(acrylicpaintYWNyeWxpY3BhaW50)''acrylic paint''' where material ='acrylic pain';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(birchwoodYmlyY2h3b29k)''birch wood''' where material ='birch wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(metalbWV0YWw)''metal''' where material ='metal';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(hornaG9ybg)''horn''' where material ='horn';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(pandanuscGFuZGFudXM)''pandanus''' where material ='pandanus fibre';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(porcelaincG9yY2VsYWlu)''porcelain''' where material ='porcelain';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(silverc2lsdmVy)''silver''' where material ='silver';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(aluminiumYWx1bWluaXVt)''aluminium''' where material ='aluminium';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(molavewoodbW9sYXZld29vZA)''molave wood''' where material ='molave wood';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(terracottadGVycmFjb3R0YQ)''terracotta''' where material ='terracotta';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(PlexiglasUGxleGlnbGFz)''Plexiglas''' where material ='plexiglass';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(plastercGxhc3Rlcg)''plaster''' where material ='plaster';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(stringc3RyaW5n)''string''' where material ='String';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cowrieY293cmll)''cowrie''' where material ='crowies';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(cottonY290dG9u)''cotton''' where material ='cotton û hand woven, dyed with indigo';
update materialgroup set material = 'urn:cspace:collection.watermillcenter.org:conceptauthorities:name(material_ca):item:name(filmZmlsbQ)''film''' where material ='film';
